---
- name: Setup HTTPD on Linux Server
  hosts: myweb
  
  tasks:
  - name: httpd package is present
    yum: 
      name: httpd
      state: present
    
  - name: correct index.html is present      
    copy:
      content: "My website created by Ansible"
      dest: /var/www/html/index.html
    
  - name: httpd is started      
    service: 
      name: httpd
      state: started
      enabled: true

