---
- name: Setup HTTPD on Linux Server
  hosts: webserver
  become: yes
  
  tasks:
  - name: httpd package is present
    yum: 
      name: httpd
      state: present
    
  - block:
      - name: correct index.html is present      
        copy:
          src: myindex.html
          dest: /var/www/html/index.html
          
      - name: update httpd.conf file
        copy:
          src: /home/devops/project1/config/master_httpd.conf
          dest: /etc/httpd/conf/httpd.conf
        notify: "restart http"
        
      - name: httpd is started      
        service: 
          name: httpd
          state: started
          enabled: true
    when: ansible_distribution == "CentOS"
  
  handlers:
  - name: "restart http"       
    service: 
      name: httpd
      state: restarted

      