---
- name: Install package on Linux Server
  hosts: [webserver, db_servers]
  become: yes
  vars_files:
    - vars/common_vars.yml
  
  tasks:
  - name: Install required package
    yum: 
      name: "{{ pkg_name }}"
      state: present

  - name: Start services
    service:
      name: "{{ service_name }}"
      status: "{{ service_status }}"
      enabled: true