---
- name: MOTD deployment through template
  hosts: all
  become: true

  tasks:
  - name: Update MOTD by Jinja2 Template
    template:
      src: ./template/motd_template.j2
      dest: /etc/motd
